services:
  mongo:
    image: mongo:6
    container_name: dailytrends_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    container_name: dailytrends_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/dailytrends
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev  # for development
    # change to "npm start" for production

volumes:
  mongo_data:
